config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'
  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

  root 'courses#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
class Coursera
    include HTTParty
  
    base_uri 'https://api.coursera.org/api/courses.v1'
    #base_uri 'https://api.coursera.org/api/catalog.v1/courses'
    #default_params fields: "smallIcon,shortDescription", q: "search"
    default_params fields: "courseType, name", q: "search"
    format :json
  
    def self.for term
      get("", query: { query: term})["elements"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
  class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'Python'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ["Alex", "Joe", "Michael"]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end

  # def goodbye
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time(time)
        # time string in AM/PM format
        time.strftime("%I:%M%p")
    end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<table border="1">
  <tr>
  	<th>Image</th>
  	<th>Name</th>
  	<th>Description</th>
  </tr>
  <% @courses.each do |course| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td></td>
      <td><%= course["name"] %></td>
      <td><%= course["courseType"] %></td>
    </tr>
  <% end %>
</table>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> time(s)</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>